### ISSUE TITLE
Nice to have Examples Folder

### ISSUE THREAD

**Issue by yakupcemilk** [chris-montero/terra#2]
I think it would be nicer for beginners to take a brief look at examples folder.

**Comment by chris-montero** [comment]
In the following days I will create legitimate independent applications that will exist in separate repositories that people will be able to browse the code of. Those will serve as examples. I will also write a guide at some point.

**Comment by yakupcemilk** [comment]
> In the following days I will create legitimate independent applications that will exist in separate repositories that people will be able to browse the code of. Those will serve as examples. I will also write a guide at some point.

That is great! I can't wait to see it.
