### ISSUE TITLE
Requirements for Building This Project

### ISSUE THREAD

**Issue by Adem-Kurt** [chris-montero/terra#7]
I couldn’t find a list of the requirements needed to build this project. Could you please provide the necessary dependencies and tools for a successful build?

**Comment by chris-montero** [comment]
I can't be sure of what distro you're using, so I don't know what packages provide these C libraries for you, but you can take a look at the project's rockspec. In essence:
* xcb
* xcb-cursor
* xcb-keysyms
* X11
* luajit
* cairo
* xkbcommon
* xkbcommon-x11
* xcb-errors (optional)

After installing these, follow the steps in the [README for installing](https://github.com/chris-montero/terra?tab=readme-ov-file#installing)
If you try this, and you still can't build it, let me know. I would like to help you and put together a proper list of dependencies.

**Comment by Adem-Kurt** [comment]
I've installed the libraries you mentioned, but when I run `sudo luarocks make`, I get the following error:

```
Missing dependencies for terra dev-1:
   tstation ~> dev-1 (not installed)

terra dev-1 depends on lua ~> 5.1 (5.1-1 provided by VM: success)
terra dev-1 depends on lgi ~> 0.9.2-1 (0.9.2-1 installed: success)
terra dev-1 depends on tstation ~> dev-1 (not installed)
```

I tried installing the `tstation` library using `sudo luarocks install tstation`, but I got this error:

```
Error: No results matching query were found for Lua 5.1.
To check if it is available for other Lua versions, use --check-lua-versions.
```

(Note: I built LuaJIT myself.)

**Comment by Adem-Kurt** [comment]
> I've installed the libraries you mentioned, but when I run `sudo luarocks make`, I get the following error:
> 
> ```
> Missing dependencies for terra dev-1:
>    tstation ~> dev-1 (not installed)
> 
> terra dev-1 depends on lua ~> 5.1 (5.1-1 provided by VM: success)
> terra dev-1 depends on lgi ~> 0.9.2-1 (0.9.2-1 installed: success)
> terra dev-1 depends on tstation ~> dev-1 (not installed)
> ```
> 
> I tried installing the `tstation` library using `sudo luarocks install tstation`, but I got this error:
> 
> ```
> Error: No results matching query were found for Lua 5.1.
> To check if it is available for other Lua versions, use --check-lua-versions.
> ```
> 
> (Note: I built LuaJIT and Luarocks myself.)

I found the solution myself

I was able to install it using the command 

```
sudo luarocks install --server=https://luarocks.org/dev tstation
 ```
 and then successfully built it.

**Comment by chris-montero** [comment]
Yes, tstation is a small publish/subscribe library that I wrote that I intend to use in other projects as well.

But I never encountered any issues with installing it from the luarocks.org servers.

If anyone else encounters an issue like this, we might have to document this somewhere.
